#
# Hatari Dockerfile
# see https://hg.tuxfamily.org/mercurialroot/hatari/hatari/raw-file/tip/doc/manual.html#Compiling_and_running

# pull base image
FROM ubuntu:14.04

ENV HATARI_TAG v1.9.0
ENV TERM xterm

ADD data /build

RUN chmod +x /build/run.sh

RUN /build/run.sh
